export const allProjects = [
  {
    proTitle: "My-accounts",
    category: "htss",
    image: "/imgs/c1.jpg",
    mText: "This Page Includes All MY Social Media Accounts.",
    mLink: "https://mohammed-23-ham.github.io/My-Accounts/",
    // guessed repo url — update if your repo name differs
    gitLink: "https://github.com/Mohammed-23-ham/my-accounts",
  },
  {
    proTitle: "To-do-list",
    category: "react",
    image: "/imgs/c2.jpg",
    mText: "This Is A React Project To Organize Your To-Do-List.",
    mLink: "https://2o-dolist.netlify.app/",
    gitLink: "https://github.com/Mohammed-23-ham/to-do-list",
  },
  {
    proTitle: "Calculator",
    category: "js",
    image: "/imgs/calculator.jpg",
    mText: "This Is A Calculator Built With HTML + CSS + JS.",
    mLink: "https://mohammed-23-ham.github.io/calculator/",
    gitLink: "https://github.com/Mohammed-23-ham/calculator",
  },
  {
    proTitle: "XO-Game",
    category: "react",
    image: "/imgs/c3.jpg",
    mText: "A Fun XO-Game Built with React.",
    mLink: "https://luxury-mochi-31dc95.netlify.app/",
    gitLink: "https://github.com/Mohammed-23-ham/xo-game",
  },
  {
    proTitle: "Template-1",
    category: "htss",
    image: "/imgs/c4.jpg",
    mText: "Single-Page Design Built with HTML + CSS.",
    mLink: "https://mohammed-23-ham.github.io/template_one/",
    gitLink: "https://github.com/Mohammed-23-ham/template-1",
  },
  {
    proTitle: "Template-2",
    category: "htss",
    image: "/imgs/c5.jpg",
    mText: "Single-Page Design Built with HTML + CSS.",
    mLink: "https://mohammed-23-ham.github.io/HTML-CSS-Template2/",
    gitLink: "https://github.com/Mohammed-23-ham/template-2",
  },
  {
    proTitle: "Template-3",
    category: "htss",
    image: "/imgs/c6.jpg",
    mText: "Single-Page Design Built with HTML + CSS.",
    mLink: "https://mohammed-23-ham.github.io/HTML-CSS-Template3/",
    gitLink: "https://github.com/Mohammed-23-ham/template-3",
  },
  {
    proTitle: "Template-4",
    category: "htss",
    image: "/imgs/c7.jpg",
    mText: "Multi-Page Design Built with HTML + CSS.",
    mLink: "https://mohammed-23-ham.github.io/template-four/",
    gitLink: "https://github.com/Mohammed-23-ham/template-4",
  },
  {
    proTitle: "Template-5",
    category: "js",
    image: "/imgs/c8.jpg",
    mText: "Single-Page Design Built with HTML + CSS + JS.",
    mLink: "https://mohammed-23-ham.github.io/Template-five/",
    gitLink: "https://github.com/Mohammed-23-ham/template-5",
  },
  {
    proTitle: "Template-6",
    category: "js",
    image: "/imgs/c9.jpg",
    mText: "Single-Page Design Built with HTML + CSS + JS.",
    mLink: "https://mohammed-23-ham.github.io/Template-6/",
    gitLink: "https://github.com/Mohammed-23-ham/template-6",
  },
];
